[err-permission]
other = "无权操作"

[err-user-not-found]
other = "用户不存在"

[err-user-lock]
other = "用户已锁定"

[err-only-admin]
other = "仅管理员可操作"

[err-password]
other = "密码错误"

[err-invite-code-invalid]
other = "邀请码无效"

[err-email-invalid]
other = "邮箱格式错误"

[err-oauth-state-invalid]
other = "OAuth 状态无效"

[err-unsupported-platform]
other = "不支持的平台"

[err-not-invited]
other = "未被邀请"

[err-dingtalk-not-enabled]
other = "钉钉未启用"

[err-custom-not-enabled]
other = "OAuth未启用"

[err-user-limit]
other = "用户数量已达上限"

[err-invalid-secret]
other = "无效的密钥"

[err-ai-employee-limit]
other = "开源版只支持创建一个AI员工"